## Numpy Arrays
## Arange
## Zeros
## Ones
## Linspace
## Eye
## Random
## Numpy Series Methods

# NUMPY ARRAYS

In [1]:
import numpy as np

In [2]:
maList = [2,3,4,5]

print(type(maList))


<class 'list'>


In [3]:
np.array(maList)

array([2, 3, 4, 5])

In [4]:
matrixList = [[1,2,3],[50,60,70],["a","b","c"]]

In [5]:
matrixList[1][2]

70

In [6]:
np.array(matrixList)

array([['1', '2', '3'],
       ['50', '60', '70'],
       ['a', 'b', 'c']], dtype='<U11')

# ARANGE

In [ ]:
## This is important !

In [7]:
[*range(0,10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)  ## from 0(zero) to 10(ten) with step size 2(two)

array([0, 2, 4, 6, 8])

# ZEROS

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# ONES

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# LINSPACE 

In [ ]:
## This is important !

In [19]:
np.linspace(0,20,6)  ## every individual digit has the same distance

array([ 0.,  4.,  8., 12., 16., 20.])

In [21]:
np.linspace(0,10,20) ## from 0(zero) to 10(ten) 
                     ## give 20(twenty) digits with same distance

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

 # EYE

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# RANDOM

In [45]:
np.random.randn(2)   ## give me random 2(two) different digits

array([-1.42601053,  0.40701207])

In [46]:
np.random.randn(3,2)

array([[0.21139237, 1.32157094],
       [0.72349258, 0.95631566],
       [0.9399592 , 1.18373413]])

In [47]:
np.random.randint(1,20) ## from 1(one) to 20(twenty)
                        ## give me random 1(one) integer

16

In [48]:
np.random.randint(1,10,3) ## from 1(one) to 10(ten) 
                          ## give me random 3(three) different integers

array([7, 1, 5])

In [49]:
np.random.randint(1,1000,5)

array([879, 640, 923, 593, 297])

In [52]:
myNumpySeries = np.arange(20)
myNumpySeries

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
myRandomSeries = np.random.randint(0,100,5)
myRandomSeries

array([42, 53,  5, 95, 52])

# NUMPY SERIES METHODS

In [62]:
myNumpySeries.reshape(4,4)

ValueError: cannot reshape array of size 20 into shape (4,4)

In [60]:
myNumpySeries.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
myNumpySeries.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [63]:
myNumpySeries.max()

19

In [65]:
myNumpySeries.min()

0

In [64]:
myRandomSeries.max()

95

In [66]:
myRandomSeries.min()

5

In [67]:
myRandomSeries.argmax()

3

In [68]:
myRandomSeries.argmin()

2

In [69]:
myNumpySeries.shape

(20,)