## Advanced Level Of Series
## Matrix
### Slicing With Matrix Series
## Operations

# ADVANCED LEVEL OF SERIES

In [1]:
import numpy as np

In [24]:
mySeries = np.arange(0,15)
mySeries

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
type(mySeries)

numpy.ndarray

In [25]:
mySeries[5] ## we can call members of series just like list

5

In [26]:
mySeries[3:6] ## we can use "slicing" method for series just like list

array([3, 4, 5])

In [27]:
mySeries[3:6] = -5  ## we can change the "sliced" part of series
mySeries

array([ 0,  1,  2, -5, -5, -5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
otherSeries = np.arange(0,25) ## we can put series into variables
otherSeries

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
otherSeries[5:10]  ## slicing method

array([5, 6, 7, 8, 9])

In [30]:
slicingSeries = otherSeries[5:10] ## putted into a variable
slicingSeries

array([5, 6, 7, 8, 9])

In [31]:
slicingSeries[:] = 999 ## changing the all members of sliced part 
slicingSeries

array([999, 999, 999, 999, 999])

In [32]:
otherSeries ## we changed the sliced part members 
            ## and it affected the original series array

array([  0,   1,   2,   3,   4, 999, 999, 999, 999, 999,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

##### blank 

In [33]:
exampleSeries = np.arange(0,25) ## let's try it one more time
exampleSeries

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
exampleSeriesCopy = exampleSeries.copy() ## this time  
exampleSeriesCopy                        ## we create a copy series array
                                         ## for the original one
                                         ## for changing the sliced part

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
exampleSeriesCopySlicing = exampleSeriesCopy[10:20] ## we putted them into 
exampleSeriesCopySlicing                            ## another variable
                                                    ## to change

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
exampleSeriesCopySlicing[:] = 888 ## we are changing the members 
exampleSeriesCopySlicing

array([888, 888, 888, 888, 888, 888, 888, 888, 888, 888])

In [37]:
exampleSeriesCopy ## and the change, only affected the "copy" version
                  ## of the original series array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888,  20,  21,  22,  23,  24])

In [38]:
exampleSeries   ## and let's call the original 
                ## to see if anything is different 
                ## the answer is, no
                ## it is the same as original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# MATRIX

In [40]:
matrixList = [[10,20,30],[40,50,60],[70,80,90]]

In [41]:
matrixSeries = np.array(matrixList)
matrixSeries

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [42]:
matrixSeries[0][2]

30

In [43]:
matrixSeries[0,2]

30

## Slicing With Matrix Series

In [44]:
matrixSeries[1:,1] 

array([50, 80])

In [45]:
matrixSeries[0:,1]

array([20, 50, 80])

In [46]:
matrixSeries[0:,2]

array([30, 60, 90])

In [47]:
matrixSeries[2:,0]

array([70])

In [48]:
matrixSeries[2:,0:]

array([[70, 80, 90]])

In [49]:
matrixSeries[1:,1:]

array([[50, 60],
       [80, 90]])

# OPERATIONS

In [53]:
newSeries = np.random.randint(1,100,20)
newSeries

array([79,  6, 59, 33, 81,  2, 68, 43, 17, 55, 72, 19, 20, 76, 31, 98, 47,
       69, 42, 31])

In [56]:
newSeries > 25  ## it gives us the boolen answer for series members

array([ True, False,  True,  True,  True, False,  True,  True, False,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [58]:
boolenAnswers = newSeries > 30 ## we putted it into a variable
boolenAnswers 

array([ True, False,  True,  True,  True, False,  True,  True, False,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [60]:
newSeries[boolenAnswers] ## it gives us only the numbers 
                         ## which are equal to "True" in 
                         ## the variable called "boolenAnswers"

array([79, 59, 33, 81, 68, 43, 55, 72, 76, 31, 98, 47, 69, 42, 31])

##### blank

In [61]:
lastSeries = np.arange(0,25)
lastSeries

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
(lastSeries + lastSeries) 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [66]:
(lastSeries + lastSeries) * 3

array([  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
        78,  84,  90,  96, 102, 108, 114, 120, 126, 132, 138, 144])

In [68]:
(lastSeries + lastSeries) / 4

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. ])

In [69]:
(lastSeries * lastSeries) 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [70]:
(lastSeries - lastSeries) 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [72]:
(lastSeries / lastSeries) ## we cannot divide 0(zero) to 0(zero)
                          ## so, the compiler gives us an error message

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7284\336768949.py:1: RuntimeWarning: invalid value encountered in true_divide
  (lastSeries / lastSeries) ## we cannot divide 0(zero) to 0(zero)


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [74]:
np.sqrt(lastSeries) ## " sqrt " means " square root "
                    ## it gives us the square roots of the digits

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])